version: "2"
linters:
  enable:
    - bodyclose
    - errname
    - gocritic
    - misspell
    - nilerr
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - dupImport
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
        - paramTypeCombine
      enabled-tags:
        - diagnostic
        - performance
        - style
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: unexported-return
        - name: var-naming
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
          - unparam
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/devbydaniel/meetingcli
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
