version: 2

builds:
  - id: meeting
    main: ./cmd/meeting
    binary: meeting
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/devbydaniel/meetingcli/internal/version.Version={{.Version}}
      - -X github.com/devbydaniel/meetingcli/internal/version.Commit={{.Commit}}
      - -X github.com/devbydaniel/meetingcli/internal/version.Date={{.Date}}
      - -X github.com/devbydaniel/meetingcli/internal/version.BuiltBy=goreleaser

archives:
  - id: meeting
    ids:
      - meeting
    name_template: "meeting_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

brews:
  - name: meeting
    ids:
      - meeting
    repository:
      owner: devbydaniel
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/devbydaniel/meetingcli"
    description: "Record meetings, transcribe with Voxtral, and summarize with Claude"
    license: "MIT"
    dependencies:
      - name: ffmpeg
      - name: blackhole-2ch
        type: cask
